version: "3.8"
services:
  api:
    build: .
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    env_file:
      - ./.env
    environment:
      RUNTIME: DOCKER
    container_name: contract_api
    restart: unless-stopped
    depends_on:
      database:
        condition: service_started
    networks:
      - contract

  nginx:
    image: nginx
    networks:
      - contract
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started

  database:
    image: postgres:13
    container_name: postgres_database
    volumes:
      - contract_postgres_db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5431:5432
    networks:
      - contract

  redis:
    image: redis
    container_name: contract_redis
    volumes:
      - contract_redis_data:/data
    restart: unless-stopped
    networks:
      - contract

networks:
  contract:
volumes:
  node_modules:
  contract_postgres_db_data:
  contract_redis_data:
